"""empty message

Revision ID: 035454f0ff62
Revises: 8fa93214c740
Create Date: 2024-03-09 16:27:27.381231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035454f0ff62'
down_revision: Union[str, None] = '8fa93214c740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_booking_available', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('ad_booking_available', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('ad_booking_available', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('priority', sa.Column('color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('priority', 'color')
    op.drop_column('ad_booking_available', 'deleted_at')
    op.drop_column('ad_booking_available', 'updated_at')
    op.drop_column('ad_booking_available', 'created_at')
    # ### end Alembic commands ###
