"""empty message

Revision ID: 12a6aac252e3
Revises: 97ba5aa4dd64
Create Date: 2024-05-26 08:54:51.152517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a6aac252e3'
down_revision: Union[str, None] = '97ba5aa4dd64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_avatar_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'files', ['avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_avatar_id_fkey', 'users', 'avatar', ['avatar_id'], ['id'])
    # ### end Alembic commands ###