"""empty message

Revision ID: 17a9be4a3001
Revises: 12a6aac252e3
Create Date: 2024-05-26 09:38:05.816614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a9be4a3001'
down_revision: Union[str, None] = '12a6aac252e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('address', sa.String(length=254), nullable=True))
    op.alter_column('address', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('address', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('address', 'street',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('address', 'house',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'house',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('address', 'street',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('address', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('address', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('address', 'address')
    # ### end Alembic commands ###