"""empty message

Revision ID: 44c7aff4abc4
Revises: 6ad4fb43357c
Create Date: 2024-05-16 13:10:05.621062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c7aff4abc4'
down_revision: Union[str, None] = '6ad4fb43357c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('phone_codes_code_key', 'phone_codes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('phone_codes_code_key', 'phone_codes', ['code'])
    # ### end Alembic commands ###