"""empty message

Revision ID: 55bff269a47c
Revises: ceec50efa0f4
Create Date: 2024-03-21 16:46:24.075911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bff269a47c'
down_revision: Union[str, None] = 'ceec50efa0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__ad_booking_available',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ad_booking_available_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_booking_available_id'], ['ad_booking_available.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['advertisement.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ad_booking_available_id')
    )
    op.drop_table('advertisement__ad_booking_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement__ad_booking_available',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ad_booking_available_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ad_booking_available_id'], ['ad_booking_available.id'], name='advertisement__ad_booking_availabl_ad_booking_available_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['advertisement.id'], name='advertisement__ad_booking_available_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'ad_booking_available_id', name='advertisement__ad_booking_available_pkey')
    )
    op.drop_table('user__ad_booking_available')
    # ### end Alembic commands ###
