"""empty message

Revision ID: 766c41de4802
Revises: c94e2d825b2c
Create Date: 2024-02-27 22:53:55.164411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766c41de4802'
down_revision: Union[str, None] = 'c94e2d825b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photo', 'photo_thumb',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('review', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('photo', 'photo_thumb',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
