"""added files table

Revision ID: 80753edac5d8
Revises: 2b852d862c4a
Create Date: 2024-03-29 20:50:04.923625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80753edac5d8'
down_revision: Union[str, None] = '2b852d862c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disk', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('advertisement', 'auto_booking',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisement', 'auto_booking',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('files')
    # ### end Alembic commands ###