
"""added accounts and account transactions

Revision ID: 89ff2b6933c1
Revises: 523c0824f859
Create Date: 2024-03-27 15:05:05.255251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ff2b6933c1'
down_revision: Union[str, None] = '523c0824f859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisement', 'auto_booking',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisement', 'auto_booking',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###