"""empty message

Revision ID: a01d729564f4
Revises: 
Create Date: 2024-02-08 20:54:28.129827

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01d729564f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_status',
    sa.Column('is_shown', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_status_is_shown'), 'ad_status', ['is_shown'], unique=False)
    op.create_index(op.f('ix_ad_status_title'), 'ad_status', ['title'], unique=True)
    op.create_table('ad_tag',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('ad_type',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_type_title'), 'ad_type', ['title'], unique=True)
    op.create_table('avatar',
    sa.Column('photo_path', sa.String(), nullable=False),
    sa.Column('photo_thumb', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_info',
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_status',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_status_title'), 'booking_status', ['title'], unique=True)
    op.create_table('booking_type',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_type_title'), 'booking_type', ['title'], unique=True)
    op.create_table('category',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('meta_title', sa.String(), nullable=False),
    sa.Column('meta_description', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('bookable', sa.Boolean(), nullable=False),
    sa.Column('map_addressable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_title'), 'city', ['title'], unique=True)
    op.create_table('country',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_title'), 'country', ['title'], unique=True)
    op.create_table('filter_type',
    sa.Column('functional_title', sa.String(length=256), nullable=False),
    sa.Column('interval_placeholder_from', sa.String(length=32), nullable=True),
    sa.Column('interval_placeholder_to', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_type_functional_title'), 'filter_type', ['functional_title'], unique=True)
    op.create_table('photo',
    sa.Column('photo_path', sa.String(), nullable=False),
    sa.Column('photo_thumb', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priority',
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priority_title'), 'priority', ['title'], unique=True)
    op.create_table('token',
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_type',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_type_title'), 'transaction_type', ['title'], unique=True)
    op.create_table('user_field',
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_title'), 'user_role', ['title'], unique=True)
    op.create_table('user_status',
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_status_title'), 'user_status', ['title'], unique=True)
    op.create_table('weekday',
    sa.Column('short_title', sa.String(length=8), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_title')
    )
    op.create_index(op.f('ix_weekday_title'), 'weekday', ['title'], unique=True)
    op.create_table('address',
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(length=64), nullable=True),
    sa.Column('house', sa.String(length=32), nullable=True),
    sa.Column('flat', sa.String(length=16), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filter',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('filter_type_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['filter_type_id'], ['filter_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('user_status_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatar.id'], ),
    sa.ForeignKeyConstraint(['user_status_id'], ['user_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('advertisement',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('user_description', sa.Text(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ad_status_id', sa.Integer(), nullable=False),
    sa.Column('ad_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['ad_status_id'], ['ad_status.id'], ),
    sa.ForeignKeyConstraint(['ad_type_id'], ['ad_type.id'], ),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category__filter',
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['filter_id'], ['filter.id'], ),
    sa.PrimaryKeyConstraint('filter_id', 'category_id')
    )
    op.create_table('filter_value',
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('hint_html', sa.String(length=256), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['filter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user__user_field',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_field_id'], ['user_field.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'user_field_id')
    )
    op.create_table('user_notification',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Text(), nullable=False),
    sa.Column('notification_content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_booking_available',
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('time_from', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=False),
    sa.Column('min_booking_time', sa.Interval(), nullable=False),
    sa.Column('max_booking_time', sa.Interval(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_favourite',
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_photo',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_priority',
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['priority.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisement__ad_tag',
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('ad_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_tag_id'], ['ad_tag.id'], ),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.PrimaryKeyConstraint('advertisement_id', 'ad_tag_id')
    )
    op.create_table('advertisement__category',
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('advertisement_id', 'category_id')
    )
    op.create_table('advertisement__filter_value',
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('filter_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.ForeignKeyConstraint(['filter_value_id'], ['filter_value.id'], ),
    sa.PrimaryKeyConstraint('advertisement_id', 'filter_value_id')
    )
    op.create_table('booking',
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time_from', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=False),
    sa.Column('booking_status_id', sa.Integer(), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.ForeignKeyConstraint(['booking_status_id'], ['booking_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('remote_id', sa.String(), nullable=False),
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['transaction_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('view',
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worktime',
    sa.Column('weekday_id', sa.Integer(), nullable=False),
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.ForeignKeyConstraint(['weekday_id'], ['weekday.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worktime')
    op.drop_table('view')
    op.drop_table('transaction')
    op.drop_table('review')
    op.drop_table('booking')
    op.drop_table('advertisement__filter_value')
    op.drop_table('advertisement__category')
    op.drop_table('advertisement__ad_tag')
    op.drop_table('ad_priority')
    op.drop_table('ad_photo')
    op.drop_table('ad_favourite')
    op.drop_table('ad_booking_available')
    op.drop_table('user_notification')
    op.drop_table('user__user_field')
    op.drop_table('filter_value')
    op.drop_table('category__filter')
    op.drop_table('advertisement')
    op.drop_table('users')
    op.drop_table('filter')
    op.drop_table('address')
    op.drop_index(op.f('ix_weekday_title'), table_name='weekday')
    op.drop_table('weekday')
    op.drop_index(op.f('ix_user_status_title'), table_name='user_status')
    op.drop_table('user_status')
    op.drop_index(op.f('ix_user_role_title'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_table('user_field')
    op.drop_index(op.f('ix_transaction_type_title'), table_name='transaction_type')
    op.drop_table('transaction_type')
    op.drop_table('token')
    op.drop_index(op.f('ix_priority_title'), table_name='priority')
    op.drop_table('priority')
    op.drop_table('photo')
    op.drop_index(op.f('ix_filter_type_functional_title'), table_name='filter_type')
    op.drop_table('filter_type')
    op.drop_index(op.f('ix_country_title'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_city_title'), table_name='city')
    op.drop_table('city')
    op.drop_table('category')
    op.drop_index(op.f('ix_booking_type_title'), table_name='booking_type')
    op.drop_table('booking_type')
    op.drop_index(op.f('ix_booking_status_title'), table_name='booking_status')
    op.drop_table('booking_status')
    op.drop_table('booking_info')
    op.drop_table('avatar')
    op.drop_index(op.f('ix_ad_type_title'), table_name='ad_type')
    op.drop_table('ad_type')
    op.drop_table('ad_tag')
    op.drop_index(op.f('ix_ad_status_title'), table_name='ad_status')
    op.drop_index(op.f('ix_ad_status_is_shown'), table_name='ad_status')
    op.drop_table('ad_status')
    # ### end Alembic commands ###
