"""empty message

Revision ID: bd1b8f647df4
Revises: 00236b9853e9
Create Date: 2024-03-10 17:14:40.253232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1b8f647df4'
down_revision: Union[str, None] = '00236b9853e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_message_attachements_chat_message_id_fkey', 'chat_message_attachements', type_='foreignkey')
    op.create_foreign_key(None, 'chat_message_attachements', 'chat_messages', ['chat_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_message_attachements', type_='foreignkey')
    op.create_foreign_key('chat_message_attachements_chat_message_id_fkey', 'chat_message_attachements', 'chats', ['chat_message_id'], ['id'])
    # ### end Alembic commands ###
