"""empty message

Revision ID: c2edc61a9c98
Revises: 55bff269a47c
Create Date: 2024-03-21 16:50:50.504814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2edc61a9c98'
down_revision: Union[str, None] = '55bff269a47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__ad_booking_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__ad_booking_available',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ad_booking_available_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ad_booking_available_id'], ['ad_booking_available.id'], name='user__ad_booking_available_ad_booking_available_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['advertisement.id'], name='user__ad_booking_available_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'ad_booking_available_id', name='user__ad_booking_available_pkey')
    )
    # ### end Alembic commands ###
