"""empty message

Revision ID: c94e2d825b2c
Revises: cf02c79e2f8a
Create Date: 2024-02-27 22:40:25.735327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c94e2d825b2c'
down_revision: Union[str, None] = 'cf02c79e2f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('priority', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('review', 'date')
    op.alter_column('weekday', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekday', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('review', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('priority', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
