"""empty message

Revision ID: cc8cbb29d2be
Revises: 80753edac5d8
Create Date: 2024-05-13 09:26:26.419098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8cbb29d2be'
down_revision: Union[str, None] = '80753edac5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ad_photo_photo_id_fkey', 'ad_photo', type_='foreignkey')
    op.create_foreign_key(None, 'ad_photo', 'files', ['photo_id'], ['id'])
    op.drop_column('ad_photo', 'id')
    op.drop_column('ad_photo', 'is_main')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_photo', sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ad_photo', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'ad_photo', type_='foreignkey')
    op.create_foreign_key('ad_photo_photo_id_fkey', 'ad_photo', 'photo', ['photo_id'], ['id'])
    # ### end Alembic commands ###