"""empty message

Revision ID: e449c91a5167
Revises: a01d729564f4
Create Date: 2024-02-16 14:46:56.955273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e449c91a5167'
down_revision: Union[str, None] = 'a01d729564f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter_type', sa.Column('title', sa.String(length=256), nullable=False))
    op.create_index(op.f('ix_filter_type_title'), 'filter_type', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filter_type_title'), table_name='filter_type')
    op.drop_column('filter_type', 'title')
    # ### end Alembic commands ###
