"""empty message

Revision ID: eacabf1eecf1
Revises: b5ff26a2e0f2
Create Date: 2024-05-13 11:28:05.119110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eacabf1eecf1'
down_revision: Union[str, None] = 'b5ff26a2e0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_favourite', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_favourite', 'id')
    # ### end Alembic commands ###